LOCATION_TIMEZONE = "IANA Time Zone"
LOCATION_LONGITUDE = "Longitude in decimal degrees"
LOCATION_LATITUDE = "Latitude in decimal degrees"
LOCATION_HEIGHT = "Height in meters"
CHECK_TIME = "Time format HH:MM:SS"
LAMP_OFF_TIME = "Time format HH:MM:SS"
ON_RANGE = "Time format HH:MM:SS"
OFF_RANGE = "Time format HH:MM:SS"
HELIOS_WEBSERVICE = "Helios Web Service URL"
AIO_USERNAME = "Adafruit IO username"
AIO_KEY = "Adafruit IO key"
AIO_GROUP = "Adafruit IO feed group"
